# Site settings
title: Ldd's Blog
email: leonardoldd@gmail.com
twitter_username: _ldd
github_username:  ldd
base_url: "ldd.github.io"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
#highlighter: rouge //fix for windows (probably not needed anymore)