# Site settings
title: Ldd's Blog
email: leonardoldd@gmail.com
baseurl: ""
url: ""
twitter_username: _ldd
github_username:  ldd

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]
#highlighter: rouge